Repository mavlink/MAVSDK, pull requests merged in 2018-05, with the labels that each got.

#375 Serial connection support for Windows
  core/CMakeLists.txt
  core/cli_arg.cpp
  core/cli_arg.h
  core/cli_arg_test.cpp
  core/dronecore.cpp
  core/dronecore.h
  core/dronecore_impl.cpp
  core/dronecore_impl.h
  core/log.cpp
  core/log.h
  core/serial_connection.cpp
  core/serial_connection.h
  core/udp_connection.cpp
  core/udp_connection.h
  example/fly_mission/fly_mission.cpp
  example/takeoff_land/takeoff_and_land.cpp
  plugins/follow_me/follow_me_impl.cpp
Labels: in progress

#379 backend: fix warning coming with new AppleClang
  backend/src/plugins/telemetry/telemetry_service_impl.h
Labels: grpc

#383 core: fix conversion that now generates a warning
  core/mavlink_parameters.h
Labels: in progress

#377 Add action features
  backend/src/plugins/action/action_service_impl.h
  backend/test/action_service_impl_test.cpp
  plugins/action/mocks/action_mock.h
Labels: grpc, in progress

#384 core: fix bad-cast on param_get fail
  core/mavlink_system.cpp
Labels: in progress

#386 build_system: build tinyxml2 statically
  CMakeLists.txt
  appveyor.yml
  cmake/compiler_flags.cmake
  cmake/tinyxml2.cmake
  core/integration_test_helper.h
  integration_tests/CMakeLists.txt
Labels: in progress

#390 core: use 251 as compid
  core/mavlink_system.h
Labels: in progress

#400 Make all examples use add_any_connection()
  example/fly_mission/fly_mission.cpp
  example/fly_qgc_mission/fly_qgc_mission.cpp
  example/follow_me/follow_me.cpp
  example/offboard_velocity/offboard_velocity.cpp
  example/takeoff_land/takeoff_and_land.cpp
  example/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp
Labels: in progress

#409 Implement camera backend
  backend/src/plugins/camera/camera_service_impl.h
  backend/test/camera_service_impl_test.cpp
  plugins/camera/mocks/camera_mock.h
Labels: grpc
