Repository mavlink/MAVSDK, pull requests merged in 2018-04, with the labels that each got.

#349 mission plugin: Clear old mission items
  plugins/mission/mission_impl.cpp
Labels: in progress, plugins

#351 Add support for COMMAND_INT and abstraction for the same including `COMMAND_LONG`
  core/mavlink_commands.cpp
  core/mavlink_commands.h
  core/mavlink_system.cpp
  core/mavlink_system.h
  plugins/action/action_impl.cpp
  plugins/gimbal/gimbal_impl.cpp
  plugins/logging/logging_impl.cpp
  plugins/mission/mission_impl.cpp
  plugins/mission/mission_impl.h
  plugins/mission/mission_import_qgc_test.cpp
Labels: core, feature request, in progress, plugins

#354 build_system: remove unused-parameter flag for AppleClang
  CMakeLists.txt
  cmake/compiler_flags.cmake
Labels: in progress

#352 backend: add packaging scripts for iOS
  backend/tools/README.md
  backend/tools/package_backend_framework.bash
  backend/tools/push_backend_framework_to_s3.bash
Labels: in progress

#356 Added YCM conf file for vim YouCompleteMe
  .ycm_extra_conf.py
Labels: in progress

#357 backend: improve backend api and initialization
  backend/src/CMakeLists.txt
  backend/src/backend.cpp
  backend/src/backend.h
  backend/src/backend_api.cpp
  backend/src/backend_api.h
  backend/src/connection_initiator.h
  backend/src/dronecore_server.cpp
  backend/src/grpc_server.cpp
  backend/src/grpc_server.h
Labels: in progress

#362 backend: add health to telemetry
  backend/src/plugins/telemetry/telemetry_service_impl.h
  backend/test/telemetry_service_impl_test.cpp
  plugins/telemetry/mocks/telemetry_mock.h
  plugins/telemetry/telemetry.cpp
  plugins/telemetry/telemetry.h
Labels: grpc, in progress

#360 core: notify already-connected systems on register_on_discover
  core/dronecore.h
  core/dronecore_impl.cpp
  core/mavlink_system.cpp
Labels: in progress

#370 build_system: fix make clean
  Makefile
Labels: in progress

#371 Add telemetry features
  backend/src/plugins/telemetry/telemetry_service_impl.h
  backend/test/telemetry_service_impl_test.cpp
  plugins/telemetry/mocks/telemetry_mock.h
  plugins/telemetry/telemetry.cpp
  plugins/telemetry/telemetry.h
Labels: grpc, in progress

#372 Serial connection support for macOS
  cmake/compiler_flags.cmake
  core/dronecore.h
  core/dronecore_impl.cpp
  core/serial_connection.cpp
  core/serial_connection.h
  example/fly_mission/CMakeLists.txt
  example/fly_mission/fly_mission.cpp
Labels: in progress
