Repository mavlink/MAVSDK, pull requests merged in 2019-12, with the labels that each got.

#920 core: Fix if else typo in mavlink_parameters
  src/core/mavlink_parameters.h
Labels: enhancement

#919 Add missing const around core and integration_tests
  src/core/udp_connection.cpp
  src/integration_tests/camera_settings.cpp
Labels: enhancement

#921 core: Use std::any_of in system_impl
  src/core/system_impl.cpp
Labels: enhancement

#918 core: Add missing override for tcp, udp and serial connection
  src/core/serial_connection.h
  src/core/tcp_connection.h
  src/core/udp_connection.h
Labels: enhancement

#922 Add configuration to run MAVSDK on the autopilot side
  src/core/mavsdk.h
  src/core/mavsdk_impl.cpp
  src/core/udp_connection.cpp
Labels: feature

#923 Set listening port of mavsdk_server in order to run multiple instances in parallel
  src/backend/src/backend.cpp
  src/backend/src/backend.h
  src/backend/src/backend_api.cpp
  src/backend/src/backend_api.h
  src/backend/src/connection_initiator.h
  src/backend/src/grpc_server.cpp
  src/backend/src/grpc_server.h
  src/backend/src/mavsdk_server.cpp
Labels: feature

#928 Only build libmavsdk_server.so for Android (and not mavsdk_server)
  src/backend/src/CMakeLists.txt
Labels: enhancement

#935 core: fix segfault on register_plugin
  src/core/system_impl.cpp
  src/core/system_impl.h
Labels: bug

#941 Improve error handling in changelog generator script
  tools/generate_changelog.py
Labels: enhancement
