Repository mavlink/MAVSDK, pull requests merged in 2019-10, with the labels that each got.

#870 Enable geofence in mavsdk_server
  src/backend/src/CMakeLists.txt
  src/backend/src/grpc_server.cpp
  src/backend/src/grpc_server.h
  src/plugins/geofence/include/plugins/geofence/geofence.h
Labels: feature

#875 remove MANYLINUX option now that dockcross declares it
  .travis.yml
  CMakeLists.txt
  third_party/cmake/build_target.cmake
  third_party/grpc/CMakeLists.txt
Labels: improvement

#877 Update grpc to 1.24.0
  src/backend/src/generated/action/action.grpc.pb.cc
  src/backend/src/generated/action/action.grpc.pb.h
  src/backend/src/generated/calibration/calibration.grpc.pb.cc
  src/backend/src/generated/calibration/calibration.grpc.pb.h
  src/backend/src/generated/camera/camera.grpc.pb.cc
  src/backend/src/generated/camera/camera.grpc.pb.h
  src/backend/src/generated/core/core.grpc.pb.cc
  src/backend/src/generated/core/core.grpc.pb.h
  src/backend/src/generated/geofence/geofence.grpc.pb.cc
  src/backend/src/generated/geofence/geofence.grpc.pb.h
  src/backend/src/generated/gimbal/gimbal.grpc.pb.cc
  src/backend/src/generated/gimbal/gimbal.grpc.pb.h
  src/backend/src/generated/gimbal/gimbal.pb.cc
  src/backend/src/generated/gimbal/gimbal.pb.h
  src/backend/src/generated/info/info.grpc.pb.cc
  src/backend/src/generated/info/info.grpc.pb.h
  src/backend/src/generated/mission/mission.grpc.pb.cc
  src/backend/src/generated/mission/mission.grpc.pb.h
  src/backend/src/generated/offboard/offboard.grpc.pb.cc
  src/backend/src/generated/offboard/offboard.grpc.pb.h
  src/backend/src/generated/param/param.grpc.pb.cc
  src/backend/src/generated/param/param.grpc.pb.h
  src/backend/src/generated/telemetry/telemetry.grpc.pb.cc
  src/backend/src/generated/telemetry/telemetry.grpc.pb.h
  third_party/grpc/CMakeLists.txt
  tools/generate_from_protos.sh
Labels: improvement

#880 Remove default build in ios and ios_simulator in CI
  .travis.yml
Labels: improvement

#881 Update libressl to 3.0.1
  third_party/libressl/CMakeLists.txt
Labels: improvement

#882 integration_tests: fix intermittent test fail
  src/integration_tests/mavlink_passthrough.cpp
Labels: bug

#883 Remove unused dependencies
  third_party/boringssl/CMakeLists.txt
  third_party/openssl/CMakeLists.txt
Labels: improvement

#888 add linux-armv7 to travis
  .travis.yml
Labels: improvement

#886 Remove switching to HOLD mode before arm and takeoff
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/plugins/action/action_impl.cpp
  src/plugins/action/action_impl.h
  src/plugins/telemetry/telemetry_impl.cpp
  src/plugins/telemetry/telemetry_impl.h
Labels: enhancement

#878 Add shell plugin
  src/backend/src/CMakeLists.txt
  src/backend/src/core/core_service_impl.h
  src/backend/src/generated/shell/shell.grpc.pb.cc
  src/backend/src/generated/shell/shell.grpc.pb.h
  src/backend/src/generated/shell/shell.pb.cc
  src/backend/src/generated/shell/shell.pb.h
  src/backend/src/grpc_server.cpp
  src/backend/src/grpc_server.h
  src/backend/src/plugins/shell/shell_service_impl.h
  src/plugins/CMakeLists.txt
  src/plugins/shell/CMakeLists.txt
  src/plugins/shell/include/plugins/shell/shell.h
  src/plugins/shell/mocks/shell_mock.h
  src/plugins/shell/shell.cpp
  src/plugins/shell/shell_impl.cpp
  src/plugins/shell/shell_impl.h
  tools/generate_from_protos.sh
Labels: feature

#891 Publish Windows artefacts
  .travis.yml
  src/backend/src/CMakeLists.txt
  src/backend/src/plugins/mocap/mocap_service_impl.h
  src/backend/test/telemetry_service_impl_test.cpp
  src/cmake/compiler_flags.cmake
  src/integration_tests/mavlink_ftp.cpp
  src/integration_tests/telemetry_async.cpp
  src/plugins/mavlink_ftp/fs.cpp
  src/plugins/mavlink_ftp/mavlink_ftp_impl.cpp
  src/plugins/mavlink_ftp/mavlink_ftp_impl.h
  src/plugins/mavlink_ftp/stackoverflow_unistd.h
  src/plugins/mavlink_ftp/tronkko_dirent.h
  src/plugins/mocap/include/plugins/mocap/mocap.h
  src/plugins/shell/shell_impl.cpp
  tools/style-ignore.txt
Labels: enhancement
