Repository mavlink/MAVSDK, pull requests merged in 2020-03, with the labels that each got.

#1002 add compiler definition for Android
  src/cmake/compiler_flags.cmake
Labels: bug

#1005 add pollin to serial connection read
  src/core/serial_connection.cpp
Labels: bug

#1004 Add api to stop `mavsdk_server`
  src/backend/src/backend.cpp
  src/backend/src/backend.h
  src/backend/src/backend_api.cpp
  src/backend/src/backend_api.h
  src/backend/src/grpc_server.cpp
  src/backend/src/grpc_server.h
  src/backend/src/mavsdk_server.cpp
Labels: enhancement

#1009 Fix style check in CI
  .clang-format
  docker/Dockerfile-Ubuntu-16.04
  docker/Dockerfile-Ubuntu-18.04
  tools/fix_style.sh
  tools/run-docker.sh
  tools/travis-docker-build.sh
Labels: bug, ci

#1006 Add mission set current item feature
  src/core/mavlink_mission_transfer.cpp
  src/core/mavlink_mission_transfer.h
  src/core/mavlink_mission_transfer_test.cpp
  src/plugins/mission/include/plugins/mission/mission.h
  src/plugins/mission/mission_impl.cpp
Labels: feature

#1012 Takeoff landed state
  examples/offboard_velocity/offboard_velocity.cpp
Labels: enhancement
