Repository mavlink/MAVSDK, pull requests merged in 2020-08, with the labels that each got.

#1160 manual_control example improvements
  examples/manual_control/manual_control.cpp
Labels: enhancement

#1159 Delete empty file if remote file does not exist
  src/plugins/ftp/ftp_impl.cpp
  src/plugins/ftp/ftp_impl.h
Labels: bug

#1169 Disable timesync by default
  src/core/system.cpp
  src/core/system.h
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/core/timesync.cpp
  src/core/timesync.h
Labels: enhancement

#1163 Added QGC complex mission item importing
  src/plugins/mission/mission_impl.cpp
  src/plugins/mission/mission_impl.h
  src/plugins/mission/mission_import_qgc_test.cpp
  src/plugins/mission/qgroundcontrol_sample_with_survey.plan
Labels: feature

#1174 Fix serial connection on windows
  src/core/cli_arg.cpp
Labels: bug

#1119 Initial Support for Yuneec E30Z
  src/plugins/camera/camera_definition_files/e30z.xml
  src/plugins/camera/camera_definition_files/generated/camera_definition_files.cpp
  src/plugins/camera/camera_definition_files/generated/camera_definition_files.h
  src/plugins/camera/camera_impl.cpp
Labels: feature

#1175 Fix CI
  .github/workflows/main.yml
  docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11
  src/core/cli_arg.cpp
  src/core/serial_connection.cpp
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/integration_tests/action_hover_sync.cpp
  src/integration_tests/integration_test_helper.h
  src/integration_tests/mavlink_passthrough.cpp
  src/integration_tests/telemetry_modes.cpp
  src/plugins/follow_me/follow_me_impl.cpp
  src/plugins/follow_me/follow_me_impl.h
  src/plugins/ftp/ftp_impl.cpp
  src/plugins/ftp/ftp_impl.h
  src/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
  src/plugins/mission/mission_impl.cpp
Labels: bug, ci

#1168 Update Configuration for indep. control of sysid, compid, usage_type.
  src/core/mavsdk.cpp
  src/core/mavsdk.h
  src/core/mavsdk_impl.cpp
Labels: enhancement

#1177 Remove sysid from UDP remotes, which induced duplicated messages
  src/core/udp_connection.cpp
  src/core/udp_connection.h
Labels: bug
