Repository mavlink/MAVSDK, pull requests merged in 2020-07, with the labels that each got.

#1140 Slight improvements to generate_from_protos.sh
  tools/generate_from_protos.sh
Labels: enhancement

#1142 Ubuntu/Debian packaging
  .github/workflows/main.yml
  CMakeLists.txt
  debian/.gitignore
  debian/compat
  debian/control
  debian/copyright
  debian/libmavsdk-dev.install
  debian/libmavsdk0.install
  debian/mavsdk-docs.docs
  debian/rules
  debian/source/format
  src/CMakeLists.txt
  src/cmake/Modules/FindCURL.cmake
  src/cmake/Modules/FindJsonCpp.cmake
  src/cmake/Modules/Findtinyxml2.cmake
  src/core/CMakeLists.txt
  src/plugins/action/CMakeLists.txt
  src/plugins/calibration/CMakeLists.txt
  src/plugins/camera/CMakeLists.txt
  src/plugins/follow_me/CMakeLists.txt
  src/plugins/ftp/CMakeLists.txt
  src/plugins/geofence/CMakeLists.txt
  src/plugins/gimbal/CMakeLists.txt
  src/plugins/info/CMakeLists.txt
  src/plugins/log_files/CMakeLists.txt
  src/plugins/mavlink_passthrough/CMakeLists.txt
  src/plugins/mission/CMakeLists.txt
  src/plugins/mission_raw/CMakeLists.txt
  src/plugins/mocap/CMakeLists.txt
  src/plugins/offboard/CMakeLists.txt
  src/plugins/param/CMakeLists.txt
  src/plugins/shell/CMakeLists.txt
  src/plugins/telemetry/CMakeLists.txt
  src/plugins/tune/CMakeLists.txt
  tools/generate_debian_changelog.sh
Labels: feature

#1146 workflows: use checkout action v2
  .github/workflows/main.yml
  docker/Dockerfile-Fedora-32
  docker/Dockerfile-Ubuntu-18.04
  docker/Dockerfile-Ubuntu-20.04
  docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11
  docker/build_and_push_docker_images.sh
Labels: enhancement

#1150 MAVLink FTP bugfixes
  src/plugins/ftp/ftp_impl.cpp
Labels: bug
