Repository mavlink/MAVSDK, pull requests merged in 2020-05, with the labels that each got.

#1067 Add tune plugin to backend
  src/backend/src/generated/tune/tune.grpc.pb.cc
  src/backend/src/generated/tune/tune.grpc.pb.h
  src/backend/src/generated/tune/tune.pb.cc
  src/backend/src/generated/tune/tune.pb.h
  src/backend/src/plugins/tune/tune_service_impl.h
  src/plugins/tune/include/plugins/tune/tune.h
  src/plugins/tune/tune.cpp
Labels: enhancement

#1070 Fix ftp examples compile issues
  examples/ftp_client/ftp_client.cpp
  examples/ftp_server/ftp_server.cpp
Labels: bug

#1069 Log file download improvements and fixes
  src/plugins/log_files/include/plugins/log_files/log_files.h
  src/plugins/log_files/log_files.cpp
  src/plugins/log_files/log_files_impl.cpp
  src/plugins/log_files/log_files_impl.h
Labels: enhancement

#1078 Build examples in CI
  .github/workflows/main.yml
  examples/battery/battery.cpp
  examples/calibrate/calibrate.cpp
  examples/fly_mission/fly_mission.cpp
  examples/fly_multiple_drones/fly_multiple_drones.cpp
  examples/fly_qgc_mission/fly_qgc_mission.cpp
  examples/follow_me/follow_me.cpp
  examples/ftp_server/ftp_server.cpp
  examples/geofence_inclusion/geofence_inclusion.cpp
  examples/mavshell/mavshell.cpp
  examples/multiple_drones/multiple_drones.cpp
  examples/offboard_velocity/offboard_velocity.cpp
  examples/takeoff_land/takeoff_and_land.cpp
  examples/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp
Labels: ci, enhancement

#982 third_party: update gRPC
  src/CMakeLists.txt
  third_party/grpc/CMakeLists.txt
  third_party/grpc/absl-workaround.patch
Labels: bug

#1086 generated: re-generate proto after newer grpc
  src/backend/src/generated/action/action.grpc.pb.cc
  src/backend/src/generated/action/action.grpc.pb.h
  src/backend/src/generated/calibration/calibration.grpc.pb.cc
  src/backend/src/generated/calibration/calibration.grpc.pb.h
  src/backend/src/generated/camera/camera.grpc.pb.cc
  src/backend/src/generated/camera/camera.grpc.pb.h
  src/backend/src/generated/core/core.grpc.pb.cc
  src/backend/src/generated/core/core.grpc.pb.h
  src/backend/src/generated/follow_me/follow_me.grpc.pb.cc
  src/backend/src/generated/follow_me/follow_me.grpc.pb.h
  src/backend/src/generated/ftp/ftp.grpc.pb.cc
  src/backend/src/generated/ftp/ftp.grpc.pb.h
  src/backend/src/generated/geofence/geofence.grpc.pb.cc
  src/backend/src/generated/geofence/geofence.grpc.pb.h
  src/backend/src/generated/gimbal/gimbal.grpc.pb.cc
  src/backend/src/generated/gimbal/gimbal.grpc.pb.h
  src/backend/src/generated/info/info.grpc.pb.cc
  src/backend/src/generated/info/info.grpc.pb.h
  src/backend/src/generated/log_files/log_files.grpc.pb.cc
  src/backend/src/generated/log_files/log_files.grpc.pb.h
  src/backend/src/generated/mavsdk_options.grpc.pb.cc
  src/backend/src/generated/mavsdk_options.grpc.pb.h
  src/backend/src/generated/mission/mission.grpc.pb.cc
  src/backend/src/generated/mission/mission.grpc.pb.h
  src/backend/src/generated/mission_raw/mission_raw.grpc.pb.cc
  src/backend/src/generated/mission_raw/mission_raw.grpc.pb.h
  src/backend/src/generated/mocap/mocap.grpc.pb.cc
  src/backend/src/generated/mocap/mocap.grpc.pb.h
  src/backend/src/generated/offboard/offboard.grpc.pb.cc
  src/backend/src/generated/offboard/offboard.grpc.pb.h
  src/backend/src/generated/param/param.grpc.pb.cc
  src/backend/src/generated/param/param.grpc.pb.h
  src/backend/src/generated/shell/shell.grpc.pb.cc
  src/backend/src/generated/shell/shell.grpc.pb.h
  src/backend/src/generated/telemetry/telemetry.grpc.pb.cc
  src/backend/src/generated/telemetry/telemetry.grpc.pb.h
  src/backend/src/generated/tune/tune.grpc.pb.cc
  src/backend/src/generated/tune/tune.grpc.pb.h
Labels: bug, ci

#1085 Improve output in enum operator<<
  src/plugins/action/action.cpp
  src/plugins/calibration/calibration.cpp
  src/plugins/camera/camera.cpp
  src/plugins/follow_me/follow_me.cpp
  src/plugins/ftp/ftp.cpp
  src/plugins/geofence/geofence.cpp
  src/plugins/gimbal/gimbal.cpp
  src/plugins/info/info.cpp
  src/plugins/log_files/log_files.cpp
  src/plugins/mission/mission.cpp
  src/plugins/mission_raw/mission_raw.cpp
  src/plugins/mocap/mocap.cpp
  src/plugins/offboard/offboard.cpp
  src/plugins/param/param.cpp
  src/plugins/shell/shell.cpp
  src/plugins/telemetry/telemetry.cpp
  src/plugins/tune/tune.cpp
  templates/plugin_cpp/enum.j2
Labels: enhancement

#1088 tools: don't crash on empty tags
  tools/generate_changelog.py
Labels: bug

#1092 tools: consistently use cmake -H
  tools/generate_camera_definitions.sh
  tools/generate_from_protos.sh
Labels: enhancement

#1093 backend: fix race condition for unlock
  src/backend/src/plugins/calibration/calibration_service_impl.h
  src/backend/src/plugins/camera/camera_service_impl.h
  src/backend/src/plugins/ftp/ftp_service_impl.h
  src/backend/src/plugins/log_files/log_files_service_impl.h
  src/backend/src/plugins/mission/mission_service_impl.h
  src/backend/src/plugins/mission_raw/mission_raw_service_impl.h
  src/backend/src/plugins/shell/shell_service_impl.h
  src/backend/src/plugins/telemetry/telemetry_service_impl.h
  src/backend/test/camera_service_impl_test.cpp
  templates/mavsdk_server/stream.j2
Labels: bug

#1099 Make MAVSDK build with musl
  .github/workflows/main.yml
  src/core/serial_connection.cpp
  src/plugins/ftp/fs.cpp
Labels: enhancement

#1105 Changed map to unordered_map
  src/core/call_every_handler.h
  src/core/mavlink_message_handler.h
  src/core/mavlink_parameters.h
  src/core/mavsdk_impl.h
  src/core/system_impl.h
  src/core/timeout_handler.h
  src/plugins/camera/camera_definition.cpp
  src/plugins/camera/camera_definition.h
  src/plugins/camera/camera_definition_test.cpp
  src/plugins/camera/camera_impl.cpp
  src/plugins/log_files/log_files_impl.h
  src/plugins/mission/mission_impl.cpp
Labels: enhancement

#1104 Attempt to remove some UDP connection hacks
  src/core/mavsdk_impl.cpp
  src/core/udp_connection.cpp
  src/core/udp_connection.h
Labels: enhancement

#1112 Bootstrapping of plugins from proto
  templates/cmake/call.j2
  templates/cmake/enum.j2
  templates/cmake/file.j2
  templates/cmake/request.j2
  templates/cmake/stream.j2
  templates/cmake/struct.j2
  templates/plugin_impl_cpp/call.j2
  templates/plugin_impl_cpp/enum.j2
  templates/plugin_impl_cpp/file.j2
  templates/plugin_impl_cpp/request.j2
  templates/plugin_impl_cpp/stream.j2
  templates/plugin_impl_cpp/struct.j2
  templates/plugin_impl_h/call.j2
  templates/plugin_impl_h/enum.j2
  templates/plugin_impl_h/file.j2
  templates/plugin_impl_h/request.j2
  templates/plugin_impl_h/stream.j2
  templates/plugin_impl_h/struct.j2
  tools/generate_from_protos.sh
Labels: feature

#1113 Do not ignore QGC messages
  src/core/mavsdk_impl.cpp
Labels: enhancement

#1100 telemetry: fix local position health flag
  src/plugins/telemetry/telemetry_impl.cpp
Labels: bug
