Repository mavlink/MAVSDK, pull requests merged in 2020-10, with the labels that each got.

#1200 tools: update to clang-format-10
  .github/workflows/main.yml
  docker/Dockerfile-Ubuntu-18.04
  docker/Dockerfile-Ubuntu-20.04
  examples/battery/battery.cpp
  src/backend/src/core/core_service_impl.h
  src/core/geometry.cpp
  src/core/mavlink_mission_transfer.cpp
  src/plugins/geofence/geofence_impl.cpp
  src/plugins/mission/mission_impl.cpp
  tools/fix_style.sh
  tools/run-docker.sh
Labels: enhancement

#1201 Support statustext with multiple chunks, fix calibration
  src/cmake/compiler_flags.cmake
  src/core/CMakeLists.txt
  src/core/mavlink_statustext_handler.cpp
  src/core/mavlink_statustext_handler.h
  src/core/mavlink_statustext_handler_test.cpp
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/plugins/calibration/calibration_impl.cpp
Labels: bug

#1225 iOS: build xcframework instead of fat binary
  src/backend/tools/package_backend_framework.bash
Labels: enhancement

#1226 Fix iOS release path in CI
  .github/workflows/main.yml
Labels: bug

#1231 Fix mavsdk_server start
  .github/workflows/main.yml
  src/backend/src/grpc_server.h
Labels: bug

#1232 gimbal_device_tester: tests for angular rate
  examples/gimbal_device_tester/gimbal_device_tester.cpp
Labels: enhancement

#1235 Immediately call new_system_callback if a system is already present
  src/core/mavsdk_impl.cpp
Labels: bug

#1234 Fix camera definition loading
  src/plugins/camera/camera_definition.cpp
  src/plugins/camera/camera_impl.cpp
  src/plugins/camera/camera_impl.h
Labels: bug

#1238 Gimbal device tester improvements
  examples/gimbal_device_tester/gimbal_device_tester.cpp
Labels: enhancement

#1242 Filter heartbeat in Offboard plugin to consider only autopilot heartbeats
  src/plugins/offboard/offboard_impl.cpp
Labels: enhancement

#1244 core: move sending heartbeats to Mavsdk class
  src/core/mavsdk.cpp
  src/core/mavsdk.h
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
  src/core/system_impl.cpp
  src/core/system_impl.h
Labels: enhancement

#1245 gimbal_device_tester: additional MAVLink checks
  examples/gimbal_device_tester/gimbal_device_tester.cpp
Labels: feature

#1247 Fix cam mode warnings
  src/core/mavlink_commands.cpp
  src/core/mavlink_parameters.cpp
  src/plugins/camera/camera_impl.cpp
Labels: bug

#1210 Mission: use NAV_DELAY instead of LOITER_TIME
  src/plugins/mission/mission_impl.cpp
Labels: enhancement

#1248 Fix segfault in TelemetryImpl::process_actuator_output_status
  src/plugins/telemetry/telemetry_impl.cpp
Labels: bug
