Repository mavlink/MAVSDK, pull requests merged in 2020-11, with the labels that each got.

#1249 Enable failure plugin
  src/backend/src/CMakeLists.txt
  src/backend/src/grpc_server.cpp
  src/backend/src/grpc_server.h
  src/plugins/CMakeLists.txt
Labels: feature

#1257 core: immediately call new entry
  src/core/call_every_handler.cpp
  src/core/call_every_handler.h
  src/core/call_every_handler_test.cpp
Labels: bug

#1259 Update docker: PX4 releases and bump Fedora version
  .github/workflows/main.yml
  docker/Dockerfile-Fedora-33
  docker/Dockerfile-Ubuntu-18.04-PX4-SITL-v1.10
  docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11
  docker/build_and_push_docker_images.sh
Labels: enhancement

#1260 core: fix potential race on discovery
  src/core/system_impl.cpp
Labels: bug

#1261 manual_control: use proper result if input not set
  src/plugins/manual_control/manual_control_impl.cpp
  src/plugins/manual_control/manual_control_impl.h
Labels: enhancement

#1156 core: added ping capability
  src/core/CMakeLists.txt
  src/core/ping.cpp
  src/core/ping.h
  src/core/system_impl.cpp
  src/core/system_impl.h
Labels: feature

#1266 third_party: use git apply, not patch
  src/core/mavlink_statustext_handler_test.cpp
  third_party/curl/CMakeLists.txt
  third_party/curl/curl.patch
Labels: bug

#1264 integration_tests: add test for mission_set_current
  src/core/mavlink_mission_transfer.cpp
  src/core/mavlink_mission_transfer_test.cpp
  src/integration_tests/CMakeLists.txt
  src/integration_tests/mission_set_current.cpp
Labels: enhancement

#1196 Move from C++11 to C++17 (second try)
  .github/workflows/main.yml
  .ycm_extra_conf.py
  CMakeLists.txt
  examples/CMakeLists.txt
  examples/battery/CMakeLists.txt
  examples/calibrate/CMakeLists.txt
  examples/fly_mission/CMakeLists.txt
  examples/fly_multiple_drones/CMakeLists.txt
  examples/fly_qgc_mission/CMakeLists.txt
  examples/follow_me/CMakeLists.txt
  examples/ftp_client/CMakeLists.txt
  examples/ftp_server/CMakeLists.txt
  examples/geofence_inclusion/CMakeLists.txt
  examples/manual_control/CMakeLists.txt
  examples/manual_control/joystick.cpp
  examples/mavshell/CMakeLists.txt
  examples/multiple_drones/CMakeLists.txt
  examples/offboard_velocity/CMakeLists.txt
  examples/takeoff_land/CMakeLists.txt
  examples/transition_vtol_fixed_wing/CMakeLists.txt
  examples/tune/CMakeLists.txt
  src/CMakeLists.txt
  src/backend/CMakeLists.txt
  src/backend/src/CMakeLists.txt
  src/backend/src/backend.cpp
  src/backend/src/plugins/calibration/calibration_service_impl.h
  src/backend/src/plugins/camera/camera_service_impl.h
  src/backend/src/plugins/follow_me/follow_me_service_impl.h
  src/backend/src/plugins/ftp/ftp_service_impl.h
  src/backend/src/plugins/geofence/geofence_service_impl.h
  src/backend/src/plugins/info/info_service_impl.h
  src/backend/src/plugins/log_files/log_files_service_impl.h
  src/backend/src/plugins/mission/mission_service_impl.h
  src/backend/src/plugins/mission_raw/mission_raw_service_impl.h
  src/backend/src/plugins/mocap/mocap_service_impl.h
  src/backend/src/plugins/offboard/offboard_service_impl.h
  src/backend/src/plugins/param/param_service_impl.h
  src/backend/src/plugins/telemetry/telemetry_service_impl.h
  src/backend/src/plugins/tune/tune_service_impl.h
  src/backend/test/CMakeLists.txt
  src/backend/test/camera_service_impl_test.cpp
  src/backend/test/core_service_impl_test.cpp
  src/backend/test/offboard_service_impl_test.cpp
  src/backend/test/telemetry_service_impl_test.cpp
  src/core/CMakeLists.txt
  src/core/any.h
  src/core/any_test.cpp
  src/core/mavlink_parameters.h
  src/core/system_impl.cpp
  src/plugins/camera/camera_definition_test.cpp
  src/plugins/camera/camera_impl.cpp
  src/plugins/param/param_impl.cpp
  templates/mavsdk_server/struct.j2
  third_party/CMakeLists.txt
Labels: enhancement

#1262 CI: Run iOS jobs in parallel
  .github/workflows/main.yml
Labels: enhancement

#1267 Fix Windows build when MAVSDK with SUPERBUILD is external project
  third_party/cmake/build_target.cmake
Labels: enhancement

#1269 gimbal_device_tester: switch to C++17 as well
  examples/gimbal_device_tester/CMakeLists.txt
Labels: enhancement

#1268 Add option to build macos framework
  .github/workflows/main.yml
  src/backend/src/CMakeLists.txt
  src/backend/tools/package_backend_framework.bash
Labels: feature

#1271 Handle Result as parameter
  templates/plugin_h/call.j2
  templates/plugin_h/request.j2
Labels: bug
