Repository mavlink/MAVSDK, pull requests merged in 2020-01, with the labels that each got.

#943 Add mavshell example
  example/CMakeLists.txt
  example/mavshell/CMakeLists.txt
  example/mavshell/mavshell.cpp
Labels: enhancement

#946 Add build and tests in github actions (no deployment)
  .github/workflows/main.yml
  .travis.yml
  tools/run-sitl-tests.sh
Labels: enhancement

#954 shell: fix docs build
  src/plugins/shell/include/plugins/shell/shell.h
Labels: bug, docs

#957 Adding airspeed to telemetry
  src/integration_tests/telemetry_async.cpp
  src/integration_tests/telemetry_sync.cpp
  src/plugins/telemetry/include/plugins/telemetry/telemetry.h
  src/plugins/telemetry/telemetry.cpp
  src/plugins/telemetry/telemetry_impl.cpp
  src/plugins/telemetry/telemetry_impl.h
Labels: feature

#961 mission: retry to clear the mission
  src/plugins/mission/mission_impl.cpp
Labels: bug

#963 mission: fix timeout notification
  src/plugins/mission/mission_impl.cpp
Labels: bug

#962 offboard: fix crash on plugin destruction
  src/plugins/offboard/offboard_impl.cpp
Labels: bug

#971 workflows: build PRs from forks too
  .github/workflows/main.yml
Labels: bug, ci

#972 Add mavlink parameter retry (follow up)
  src/core/mavlink_parameters.cpp
  src/core/mavlink_parameters.h
  src/plugins/telemetry/telemetry_impl.cpp
Labels: enhancement
