Repository mavlink/MAVSDK, pull requests merged in 2020-12, with the labels that each got.

#1275 core: attempt to fix connection race
  src/core/system_impl.h
Labels: bug

#1278 Fix iOS simulator build following update to Xcode 12
  src/integration_tests/follow_me.cpp
  src/mavsdk_server/src/generated/action/action.grpc.pb.cc
  src/mavsdk_server/src/generated/calibration/calibration.grpc.pb.cc
  src/mavsdk_server/src/generated/camera/camera.grpc.pb.cc
  src/mavsdk_server/src/generated/core/core.grpc.pb.cc
  src/mavsdk_server/src/generated/failure/failure.grpc.pb.cc
  src/mavsdk_server/src/generated/follow_me/follow_me.grpc.pb.cc
  src/mavsdk_server/src/generated/ftp/ftp.grpc.pb.cc
  src/mavsdk_server/src/generated/geofence/geofence.grpc.pb.cc
  src/mavsdk_server/src/generated/gimbal/gimbal.grpc.pb.cc
  src/mavsdk_server/src/generated/info/info.grpc.pb.cc
  src/mavsdk_server/src/generated/log_files/log_files.grpc.pb.cc
  src/mavsdk_server/src/generated/manual_control/manual_control.grpc.pb.cc
  src/mavsdk_server/src/generated/mission/mission.grpc.pb.cc
  src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.cc
  src/mavsdk_server/src/generated/mocap/mocap.grpc.pb.cc
  src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.cc
  src/mavsdk_server/src/generated/param/param.grpc.pb.cc
  src/mavsdk_server/src/generated/shell/shell.grpc.pb.cc
  src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.cc
  src/mavsdk_server/src/generated/tune/tune.grpc.pb.cc
  third_party/cares/CMakeLists.txt
  third_party/grpc/CMakeLists.txt
  tools/ios.toolchain.cmake
Labels: bug

#1279 Add cache to github workflows (for dependencies)
  .github/workflows/main.yml
Labels: enhancement

#1281 Add openssl
  .github/workflows/main.yml
  CMakeLists.txt
  docker/Dockerfile-Fedora-32
  docker/Dockerfile-Fedora-33
  third_party/CMakeLists.txt
  third_party/absl/CMakeLists.txt
  third_party/cares/CMakeLists.txt
  third_party/cmake/build_target.cmake
  third_party/curl/CMakeLists.txt
  third_party/grpc/CMakeLists.txt
  third_party/grpc/grpc_openssl_ios.patch
  third_party/jsoncpp/CMakeLists.txt
  third_party/libressl/CMakeLists.txt
  third_party/openssl/CMakeLists.txt
  third_party/openssl/dockcross-android.patch
  third_party/protobuf/CMakeLists.txt
  third_party/re2/CMakeLists.txt
  third_party/tinyxml2/CMakeLists.txt
  third_party/zlib/CMakeLists.txt
  tools/ios.toolchain.cmake
Labels: enhancement

#1285 core: fix missing private access modifier
  src/core/mavlink_commands.h
Labels: enhancement

#1286 core: fix CI connection race issues
  src/core/mavsdk_impl.cpp
Labels: bug

#1287 tools: support docker and podman
  tools/run-docker.sh
Labels: enhancement

#1288 Do not throw SIGPIPE when TCP connection is closed
  src/core/mavsdk_impl.cpp
  src/core/tcp_connection.cpp
  src/mavsdk_server/src/core/core_service_impl.h
Labels: bug

#1289 Add linux-armv6-musl build
  .github/workflows/main.yml
Labels: feature
