Repository mavlink/MAVSDK, pull requests merged in 2021-05, with the labels that each got.

#1426 core: use vector for systems
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
Labels: bug

#1418 Initiate UDP connection from MAVSDK
  .github/workflows/main.yml
  src/core/mavsdk_impl.cpp
  src/core/system_impl.cpp
  src/integration_tests/CMakeLists.txt
  src/integration_tests/connection.cpp
  src/integration_tests/ftp.cpp
Labels: feature

#1433 Remove wrong file
  src/backend/src/generated/action/action.grpc.pb.cc
Labels: enhancement

#1432 mission: add gimbal v2 control/release
  src/plugins/mission/mission_impl.cpp
  src/plugins/mission/mission_impl.h
Labels: bug

#1436 Update tinyxml2 to 8.1.0
  third_party/tinyxml2/CMakeLists.txt
Labels: enhancement

#1450 Minor logging improvement
  src/plugins/camera/camera_definition.cpp
Labels: enhancement

#1451 Patch tinyxml to run on stock Ubuntu 18.04 (with cmake 3.10.2)
  third_party/tinyxml2/CMakeLists.txt
  third_party/tinyxml2/cmake-3.10.2.patch
Labels: enhancement
