Repository mavlink/MAVSDK, pull requests merged in 2021-08, with the labels that each got.

#1497 Add `SET_MESSAGE_INTERVAL` support to telemetry_server publish functions
  src/core/system_impl.cpp
  src/plugins/telemetry_server/telemetry_server_impl.cpp
  src/plugins/telemetry_server/telemetry_server_impl.h
Labels: feature

#1501 Fix two warnings recently introduced
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
  src/core/system_impl.cpp
  src/plugins/mission_raw_server/mission_raw_server_impl.cpp
  src/plugins/mission_raw_server/mission_raw_server_impl.h
Labels: bug

#1502 Various commication fixes
  src/core/mavlink_commands.cpp
  src/core/mavlink_commands.h
  src/core/mavlink_include.h
  src/core/mavlink_mission_transfer.cpp
  src/core/mavlink_mission_transfer.h
  src/core/mavlink_mission_transfer_test.cpp
  src/core/mavsdk_impl.cpp
  src/core/timeout_handler.cpp
  src/plugins/camera/camera_impl.cpp
  src/plugins/gimbal/gimbal_impl.cpp
  src/plugins/mission/mission_impl.cpp
  src/plugins/telemetry/telemetry_impl.cpp
  src/plugins/telemetry/telemetry_impl.h
Labels: enhancement

#1516 Clear photo list when storage is formatted
  src/plugins/camera/camera_impl.cpp
Labels: bug

#1518 camera: fix variable shadowing
  src/plugins/camera/camera_impl.cpp
Labels: enhancement
