Repository mavlink/MAVSDK, pull requests merged in 2021-07, with the labels that each got.

#1476 Run commands in parallel
  src/core/mavlink_commands.cpp
  src/core/mavlink_commands.h
Labels: feature

#1479 core: remove deprecated UID methods
  src/core/mavlink_mission_transfer.cpp
  src/core/mavlink_mission_transfer.h
  src/core/mavlink_mission_transfer_test.cpp
  src/core/mavsdk.cpp
  src/core/mavsdk.h
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
  src/core/system.cpp
  src/core/system.h
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/debug_helpers/drop_debug_main.cpp
  src/integration_tests/action_hold.cpp
  src/integration_tests/action_hover_sync.cpp
  src/integration_tests/action_transition_multicopter_fixedwing.cpp
  src/integration_tests/integration_test_helper.h
  src/integration_tests/path_checker.h
  src/plugins/geofence/geofence_impl.cpp
  src/plugins/mission/mission_impl.cpp
  src/plugins/mission_raw/mission_raw_impl.cpp
  tools/stop_px4_sitl.sh
Labels: enhancement

#1481 workflows: prevent coveralls JS out of memory
  .github/workflows/main.yml
Labels: enhancement

#1473 Parameter Server
  src/core/mavlink_parameters.cpp
  src/core/mavlink_parameters.h
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/mavsdk_server/src/generated/param_server/param_server.grpc.pb.cc
  src/mavsdk_server/src/generated/param_server/param_server.grpc.pb.h
  src/mavsdk_server/src/generated/param_server/param_server.pb.cc
  src/mavsdk_server/src/generated/param_server/param_server.pb.h
  src/mavsdk_server/src/plugins/param_server/param_server_service_impl.h
  src/plugins/CMakeLists.txt
  src/plugins/param_server/CMakeLists.txt
  src/plugins/param_server/include/plugins/param_server/param_server.h
  src/plugins/param_server/param_server.cpp
  src/plugins/param_server/param_server_impl.cpp
  src/plugins/param_server/param_server_impl.h
Labels: feature

#1485 docker/workflows: add PX4 v1.12 release to CI
  .github/workflows/main.yml
  docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.12
  docker/build_and_push_docker_images.sh
Labels: enhancement

#1486 core: improve connection docstring
  src/core/mavsdk.h
Labels: enhancement

#1487 core: fix own sysid/compid in mission transfer
  src/core/mavlink_mission_transfer.cpp
  src/core/mavlink_mission_transfer.h
  src/core/mavlink_mission_transfer_test.cpp
  src/core/mocks/sender_mock.h
  src/core/system_impl.cpp
  src/core/system_impl.h
Labels: bug

#1489 core/plugins: detect autopilot at runtime
  src/core/mavlink_commands.cpp
  src/core/mavlink_commands.h
  src/core/mavlink_mission_transfer.cpp
  src/core/mavlink_mission_transfer.h
  src/core/mavlink_mission_transfer_test.cpp
  src/core/mocks/sender_mock.h
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/plugins/action/action_impl.cpp
  src/plugins/calibration/calibration_impl.cpp
  src/plugins/camera/camera_impl.cpp
  src/plugins/failure/failure_impl.cpp
  src/plugins/gimbal/gimbal_impl.cpp
  src/plugins/gimbal/gimbal_protocol_v1.cpp
  src/plugins/gimbal/gimbal_protocol_v2.cpp
  src/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
  src/plugins/mission/mission_impl.cpp
  src/plugins/telemetry/telemetry_impl.cpp
Labels: enhancement

#1490 core: fix autopilot detection
  src/core/system_impl.cpp
Labels: bug

#1495 core: fix mission transfer unit tests
  src/core/mavlink_mission_transfer_test.cpp
Labels: enhancement

#1482 Add telemetry_server plugin
  src/core/mavsdk_impl.h
  src/mavsdk_server/src/generated/telemetry_server/telemetry_server.grpc.pb.cc
  src/mavsdk_server/src/generated/telemetry_server/telemetry_server.grpc.pb.h
  src/mavsdk_server/src/generated/telemetry_server/telemetry_server.pb.cc
  src/mavsdk_server/src/generated/telemetry_server/telemetry_server.pb.h
  src/mavsdk_server/src/plugins/telemetry_server/telemetry_server_service_impl.h
  src/plugins/CMakeLists.txt
  src/plugins/telemetry_server/CMakeLists.txt
  src/plugins/telemetry_server/include/plugins/telemetry_server/telemetry_server.h
  src/plugins/telemetry_server/telemetry_server.cpp
  src/plugins/telemetry_server/telemetry_server_impl.cpp
  src/plugins/telemetry_server/telemetry_server_impl.h
Labels: feature
