Repository mavlink/MAVSDK, pull requests merged in 2021-06, with the labels that each got.

#1453 Identify docs generator script as Python3
  tools/generate_markdown_from_doxygen_xml.py
Labels: bug

#1455 Filter out command acks not targeted to us
  src/core/mavlink_commands.cpp
Labels: enhancement

#1461 Ignore ghost storage_information message
  src/plugins/camera/camera_impl.cpp
Labels: enhancement

#1460 core: add message debugging
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
Labels: feature

#1464 core: fix invalid sysid/compid on trimmed messages
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
Labels: bug

#1462 Remove assumption on sysids per udp packet
  src/core/udp_connection.cpp
Labels: bug

#1465 examples: fix uninitialized data
  examples/gimbal_device_tester/gimbal_device_tester.cpp
Labels: bug

#1471 Few compatibility improvements for Ardupilot
  src/core/mavlink_commands.cpp
  src/core/mavlink_commands.h
  src/core/mavlink_mission_transfer.cpp
  src/plugins/action/action_impl.cpp
  src/plugins/action/action_impl.h
  src/plugins/telemetry/telemetry_impl.cpp
Labels: feature
