Repository mavlink/MAVSDK, pull requests merged in 2021-03, with the labels that each got.

#1341 templates: impl fixes
  templates/plugin_impl_cpp/request.j2
  templates/plugin_impl_cpp/stream.j2
  templates/plugin_impl_h/stream.j2
Labels: enhancement

#1344 core: add filter for messages from QGC
  src/core/mavsdk_impl.cpp
Labels: enhancement

#1345 Gimbal improvements: added example, and v2 ROI
  examples/CMakeLists.txt
  examples/gimbal/CMakeLists.txt
  examples/gimbal/gimbal.cpp
  src/plugins/gimbal/gimbal_protocol_v1.cpp
  src/plugins/gimbal/gimbal_protocol_v2.cpp
Labels: feature

#1330 Add messages forwarding
  src/core/connection.cpp
  src/core/connection.h
  src/core/mavsdk.cpp
  src/core/mavsdk.h
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
  src/core/serial_connection.cpp
  src/core/serial_connection.h
  src/core/tcp_connection.cpp
  src/core/tcp_connection.h
  src/core/udp_connection.cpp
  src/core/udp_connection.h
Labels: feature

#1351 Add example to set camera settings
  examples/CMakeLists.txt
  examples/camera/CMakeLists.txt
  examples/camera/camera.cpp
  examples/camera_settings/CMakeLists.txt
  examples/camera_settings/camera_settings.cpp
Labels: feature

#1353 Improve realtime factor estimate
  src/core/CMakeLists.txt
  src/core/ringbuffer.h
  src/core/ringbuffer_test.cpp
  src/plugins/info/info_impl.cpp
  src/plugins/info/info_impl.h
Labels: enhancement

#1355 Update ios toolchain
  .github/workflows/main.yml
  src/plugins/gimbal/gimbal_protocol_v1.cpp
  third_party/openssl/CMakeLists.txt
  tools/ios.toolchain.cmake
Labels: feature

#1331 Add multi udp remotes
  src/core/connection.cpp
  src/core/connection.h
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
Labels: enhancement

#1358 Logfiles: test if target is an unexisting file before download
  .github/workflows/main.yml
  src/core/system_impl.cpp
  src/integration_tests/log_files.cpp
  src/plugins/log_files/CMakeLists.txt
  src/plugins/log_files/log_files_impl.cpp
  src/plugins/log_files/log_files_impl.h
Labels: enhancement

#1363 Fix "iterator not in same container" build error when compiling with MSVC2019
  src/core/mavsdk_impl.cpp
Labels: bug

#1362 core: make timeout configurable
  src/core/mavlink_commands.cpp
  src/core/mavlink_commands.h
  src/core/mavlink_mission_transfer.cpp
  src/core/mavlink_mission_transfer.h
  src/core/mavlink_mission_transfer_test.cpp
  src/core/mavlink_parameters.cpp
  src/core/mavlink_parameters.h
  src/core/mavsdk.cpp
  src/core/mavsdk.h
  src/core/mavsdk_impl.h
  src/core/system_impl.cpp
  src/core/system_impl.h
Labels: enhancement

#1370 Fix exception in integration test if no system is available
  src/integration_tests/log_files.cpp
Labels: enhancement

#1368 Switch from master/develop branches to main
  .github/workflows/main.yml
  README.md
  tools/ci-git-release.sh
Labels: enhancement

#1371 cmake: fix MSVC release build with shared libs
  src/cmake/unit_tests.cmake
Labels: bug

#1373 Propagate CMAKE_BUILD_TYPE to dependencies
  .github/workflows/main.yml
  third_party/CMakeLists.txt
  third_party/absl/CMakeLists.txt
  third_party/cares/CMakeLists.txt
  third_party/cmake/build_target.cmake
  third_party/curl/CMakeLists.txt
  third_party/grpc/CMakeLists.txt
  third_party/jsoncpp/CMakeLists.txt
  third_party/libressl/CMakeLists.txt
  third_party/openssl/CMakeLists.txt
  third_party/protobuf/CMakeLists.txt
  third_party/re2/CMakeLists.txt
  third_party/tinyxml2/CMakeLists.txt
  third_party/zlib/CMakeLists.txt
Labels: enhancement

#1375 Fix minor warning in iOS
  src/mavsdk_server/src/core/core_service_impl.h
Labels: enhancement

#1381 Remove tmpnam
  src/core/filesystem_include.h
  src/integration_tests/log_files.cpp
  src/plugins/log_files/log_files_impl.cpp
Labels: enhancement
