Repository mavlink/MAVSDK, pull requests merged in 2021-11, with the labels that each got.

#1593 MAVLink param improvements
  src/core/mavlink_parameters.cpp
  src/core/mavlink_parameters.h
  src/plugins/camera/camera_impl.cpp
Labels: enhancement

#1591 Robustify photo list
  src/core/mavlink_commands.h
  src/plugins/camera/camera_impl.cpp
Labels: bug

#1596 Fix CI permissions when generating xcframework
  src/mavsdk_server/tools/package_mavsdk_server_framework.bash
Labels: bug

#1598 Publish checksum for xcframework
  .github/workflows/main.yml
  src/mavsdk_server/tools/package_mavsdk_server_framework.bash
Labels: enhancement

#1597 camera: fix callback not called after formatting
  src/plugins/camera/camera_impl.cpp
Labels: bug

#1599 camera: request dropped IMAGE_CAPTURED messages
  src/integration_tests/CMakeLists.txt
  src/integration_tests/camera_capture_info.cpp
  src/plugins/camera/camera_impl.cpp
  src/plugins/camera/camera_impl.h
Labels: enhancement

#1601 mission: fix downloading SET_CAM_TRIGG_DIST
  src/integration_tests/mission.cpp
  src/plugins/mission/mission_impl.cpp
Labels: bug

#1602 camrea: fix first capture callback
  src/plugins/camera/camera_impl.cpp
Labels: bug

#1606 camera: handle empty camera definition URI
  src/plugins/camera/camera_impl.cpp
  src/plugins/camera/camera_impl.h
Labels: enhancement

#1604 mavsdk: add camera configuration
  src/core/mavsdk.cpp
  src/core/mavsdk.h
  src/core/mavsdk_impl.cpp
  src/core/mavsdk_impl.h
Labels: feature

#1612 camera: prevent timeout with failed images
  src/plugins/camera/camera_impl.cpp
Labels: bug

#1609 New RequestMessage class to help with requesting a single message
  src/core/CMakeLists.txt
  src/core/mavlink_commands.cpp
  src/core/mavlink_commands.h
  src/core/request_message.cpp
  src/core/request_message.h
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/integration_tests/CMakeLists.txt
  src/integration_tests/telemetry_gps_origin.cpp
  src/plugins/action/action_impl.cpp
  src/plugins/calibration/calibration_impl.cpp
  src/plugins/camera/camera_impl.cpp
  src/plugins/failure/failure_impl.cpp
  src/plugins/gimbal/gimbal_impl.cpp
  src/plugins/gimbal/gimbal_protocol_v1.cpp
  src/plugins/gimbal/gimbal_protocol_v2.cpp
  src/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
  src/plugins/mission/mission_impl.cpp
  src/plugins/telemetry/telemetry_impl.cpp
Labels: feature

#1617 core: add SystemImpl::make_command_ack_message() method
  src/core/system_impl.cpp
  src/core/system_impl.h
  src/plugins/action_server/action_server_impl.cpp
  src/plugins/telemetry_server/telemetry_server_impl.cpp
Labels: enhancement

#1619 Fix failure enums (do not cast enum values directly)
  src/plugins/failure/failure_impl.cpp
  src/plugins/failure/failure_impl.h
Labels: bug

#1622 Do not cancel SITL jobs in CI, even if another one failed
  .github/workflows/main.yml
Labels: enhancement

#1621 Fix battery voltage
  src/plugins/telemetry/telemetry_impl.cpp
Labels: bug

#1623 Use modern numeric limits
  examples/battery/battery.cpp
  src/core/cli_arg.cpp
  src/core/mavlink_channels_test.cpp
  src/plugins/telemetry/telemetry_impl.cpp
Labels: enhancement

#1613 mission: fix jsoncpp cmake
  .github/workflows/main.yml
  src/cmake/fpic_toolchain.cmake
  src/plugins/mission/CMakeLists.txt
  src/plugins/mission/mission_impl.h
Labels: bug

#1631 core: only request autopilot version if autopilot
  src/core/system_impl.cpp
Labels: enhancement

#1632 mission: remove TRIGGER_CONTROL
  src/plugins/mission/mission_impl.cpp
Labels: enhancement

#1634 mission: fail if mission item is unsupported
  src/plugins/mission/mission_impl.cpp
Labels: bug

#1640 telemetry: use SYS_STATUS to determine calibration
  src/plugins/telemetry/telemetry_impl.cpp
  src/plugins/telemetry/telemetry_impl.h
Labels: enhancement

#1641 mavsdk_server_bin: parse sysid and compid from CLI
  src/mavsdk_server/src/mavsdk_server_bin.cpp
Labels: feature

#1642 core: always apply configuration
  src/core/mavsdk_impl.cpp
Labels: bug
