Repository mavlink/MAVSDK, pull requests merged in 2022-05, with the labels that each got.

#1764 Return Timeout code when timing out, instead of ConnectionError
  src/mavsdk/core/mavlink_command_sender.cpp
Labels: bug

#1771 gitmodule: remove mavlink repo
  .gitmodules
Labels: enhancement

#1773 Add version number fallback
  CMakeLists.txt
Labels: enhancement

#1777 Fix FTP test segfault
  src/mavsdk/core/mavsdk_impl.cpp
Labels: bug

#1780 telemetry: fix scope of subscription lock
  src/mavsdk/plugins/telemetry/telemetry_impl.cpp
Labels: bug

#1782 openssl: update to 1.1.1o
  third_party/openssl/CMakeLists.txt
Labels: enhancement

#1767 core: Add callback list
  src/mavsdk/core/CMakeLists.txt
  src/mavsdk/core/callback_list.h
  src/mavsdk/core/callback_list_test.cpp
Labels: feature
