Repository mavlink/MAVSDK, pull requests merged in 2022-01, with the labels that each got.

#1658 workflows: fetch git tags for version
  .github/workflows/main.yml
Labels: enhancement

#1659 tools: add option to pass build dir
  tools/generate_from_protos.sh
Labels: enhancement

#1664 calibration: handle ack for gimbal calibration
  src/mavsdk/plugins/calibration/calibration_impl.cpp
Labels: enhancement

#1663 mavlink_parameters: handle param_ext_set
  src/mavsdk/core/include/mavsdk/plugin_base.h
  src/mavsdk/core/mavlink_parameters.cpp
  src/mavsdk/core/mavlink_parameters.h
  src/mavsdk/core/system_impl.h
Labels: feature

#1666 Enable surface boat rover modes in Ardupilot
  src/mavsdk/core/system_impl.cpp
Labels: bug

#1671 docker: add arm build for library only
  .github/workflows/main.yml
  docker/Dockerfile.dockcross-linux-arm64-custom
  docker/Dockerfile.dockcross-linux-armv6-custom
  docker/Dockerfile.dockcross-linux-armv7-custom
  docker/Dockerfile.manylinux1-x64-custom
  docker/build_and_push_docker_images.sh
  tools/create_packages.sh
Labels: enhancement

#1672 cmake: fix installed include path
  src/CMakeLists.txt
  src/mavsdk/core/CMakeLists.txt
  src/mavsdk/plugins/action/CMakeLists.txt
  src/mavsdk/plugins/action/include/plugins/action/action.h
  src/mavsdk/plugins/action_server/CMakeLists.txt
  src/mavsdk/plugins/action_server/include/plugins/action_server/action_server.h
  src/mavsdk/plugins/calibration/CMakeLists.txt
  src/mavsdk/plugins/calibration/include/plugins/calibration/calibration.h
  src/mavsdk/plugins/camera/CMakeLists.txt
  src/mavsdk/plugins/camera/include/plugins/camera/camera.h
  src/mavsdk/plugins/failure/CMakeLists.txt
  src/mavsdk/plugins/failure/include/plugins/failure/failure.h
  src/mavsdk/plugins/follow_me/CMakeLists.txt
  src/mavsdk/plugins/follow_me/include/plugins/follow_me/follow_me.h
  src/mavsdk/plugins/ftp/CMakeLists.txt
  src/mavsdk/plugins/ftp/include/plugins/ftp/ftp.h
  src/mavsdk/plugins/geofence/CMakeLists.txt
  src/mavsdk/plugins/geofence/include/plugins/geofence/geofence.h
  src/mavsdk/plugins/gimbal/CMakeLists.txt
  src/mavsdk/plugins/gimbal/include/plugins/gimbal/gimbal.h
  src/mavsdk/plugins/info/CMakeLists.txt
  src/mavsdk/plugins/info/include/plugins/info/info.h
  src/mavsdk/plugins/log_files/CMakeLists.txt
  src/mavsdk/plugins/log_files/include/plugins/log_files/log_files.h
  src/mavsdk/plugins/manual_control/CMakeLists.txt
  src/mavsdk/plugins/manual_control/include/plugins/manual_control/manual_control.h
  src/mavsdk/plugins/mavlink_passthrough/CMakeLists.txt
  src/mavsdk/plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h
  src/mavsdk/plugins/mission/CMakeLists.txt
  src/mavsdk/plugins/mission/include/plugins/mission/mission.h
  src/mavsdk/plugins/mission_raw/CMakeLists.txt
  src/mavsdk/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
  src/mavsdk/plugins/mission_raw_server/CMakeLists.txt
  src/mavsdk/plugins/mission_raw_server/include/plugins/mission_raw_server/mission_raw_server.h
  src/mavsdk/plugins/mocap/CMakeLists.txt
  src/mavsdk/plugins/mocap/include/plugins/mocap/mocap.h
  src/mavsdk/plugins/offboard/CMakeLists.txt
  src/mavsdk/plugins/offboard/include/plugins/offboard/offboard.h
  src/mavsdk/plugins/param/CMakeLists.txt
  src/mavsdk/plugins/param/include/plugins/param/param.h
  src/mavsdk/plugins/param_server/CMakeLists.txt
  src/mavsdk/plugins/param_server/include/plugins/param_server/param_server.h
  src/mavsdk/plugins/server_utility/CMakeLists.txt
  src/mavsdk/plugins/server_utility/include/plugins/server_utility/server_utility.h
  src/mavsdk/plugins/shell/CMakeLists.txt
  src/mavsdk/plugins/shell/include/plugins/shell/shell.h
  src/mavsdk/plugins/telemetry/CMakeLists.txt
  src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
  src/mavsdk/plugins/telemetry_server/CMakeLists.txt
  src/mavsdk/plugins/telemetry_server/include/plugins/telemetry_server/telemetry_server.h
  src/mavsdk/plugins/tracking_server/CMakeLists.txt
  src/mavsdk/plugins/tracking_server/include/plugins/tracking_server/tracking_server.h
  src/mavsdk/plugins/transponder/CMakeLists.txt
  src/mavsdk/plugins/transponder/include/plugins/transponder/transponder.h
  src/mavsdk/plugins/tune/CMakeLists.txt
  src/mavsdk/plugins/tune/include/plugins/tune/tune.h
  templates/plugin_h/file.j2
Labels: bug

#1674 tools/workflows: fix packages for arm
  .github/workflows/main.yml
  tools/create_packages.sh
Labels: bug

#1676 docker: use arm lts images
  docker/Dockerfile.dockcross-linux-arm64-custom
  docker/Dockerfile.dockcross-linux-armv6-custom
  docker/Dockerfile.dockcross-linux-armv7-custom
Labels: enhancement

#1677 workflows: invalidate cache for arm builds
  .github/workflows/main.yml
Labels: enhancement

#1678 docker: fix tags
  docker/build_and_push_docker_images.sh
Labels: bug

#1681 tools: fix package generation
  .github/workflows/main.yml
  tools/create_packages.sh
Labels: bug

#1682 docker: fix tags again
  .github/workflows/main.yml
  docker/Dockerfile.dockcross-linux-arm64-custom
  docker/Dockerfile.dockcross-linux-armv6-custom
  docker/Dockerfile.dockcross-linux-armv7-custom
Labels: bug

#1686 core: fix linking on Windows
  src/mavsdk/core/include/mavsdk/log_callback.h
  src/mavsdk/core/log.cpp
  src/mavsdk/core/log.h
Labels: bug

#1690 Fixed XCode warning
  src/mavsdk_server/src/mavsdk_server_api.h
Labels: enhancement
