Repository mavlink/MAVSDK, pull requests merged in 2023-03, with the labels that each got.

#1995 Enable offboard plugin with Ardupilot Rover
  src/mavsdk/core/flight_mode.cpp
  src/mavsdk/core/system_impl.cpp
  src/mavsdk/plugins/offboard/offboard_impl.cpp
Labels: enhancement

#2008 [BACKPORT v1.4] mavsdk_server: link to dl
  src/mavsdk_server/src/CMakeLists.txt
  src/mavsdk_server/test/CMakeLists.txt
Labels: bug

#2011 CI: update checkout action
  .github/workflows/main.yml
Labels: enhancement

#2010 Expose params through mavlink_passthrough
  src/mavsdk/core/system_impl.cpp
  src/mavsdk/core/system_impl.h
  src/mavsdk/plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h
  src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough.cpp
  src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
  src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.h
Labels: feature

#2012 Rename _parent to _system_impl
  src/mavsdk/core/mavlink_command_sender.cpp
  src/mavsdk/core/mavlink_command_sender.h
  src/mavsdk/core/plugin_impl_base.cpp
  src/mavsdk/core/plugin_impl_base.h
  src/mavsdk/core/system_impl.cpp
  src/mavsdk/core/system_impl.h
  src/mavsdk/core/timesync.cpp
  src/mavsdk/core/timesync.h
  src/mavsdk/plugins/action/action_impl.cpp
  src/mavsdk/plugins/calibration/calibration_impl.cpp
  src/mavsdk/plugins/camera/camera_impl.cpp
  src/mavsdk/plugins/component_information/component_information_impl.cpp
  src/mavsdk/plugins/failure/failure_impl.cpp
  src/mavsdk/plugins/follow_me/follow_me_impl.cpp
  src/mavsdk/plugins/ftp/ftp_impl.cpp
  src/mavsdk/plugins/ftp/ftp_impl.h
  src/mavsdk/plugins/geofence/geofence_impl.cpp
  src/mavsdk/plugins/gimbal/gimbal_impl.cpp
  src/mavsdk/plugins/gripper/gripper_impl.cpp
  src/mavsdk/plugins/info/info_impl.cpp
  src/mavsdk/plugins/log_files/log_files_impl.cpp
  src/mavsdk/plugins/manual_control/manual_control_impl.cpp
  src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
  src/mavsdk/plugins/mission/mission_impl.cpp
  src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
  src/mavsdk/plugins/mocap/mocap_impl.cpp
  src/mavsdk/plugins/offboard/offboard_impl.cpp
  src/mavsdk/plugins/param/param_impl.cpp
  src/mavsdk/plugins/rtk/rtk_impl.cpp
  src/mavsdk/plugins/server_utility/server_utility_impl.cpp
  src/mavsdk/plugins/shell/shell_impl.cpp
  src/mavsdk/plugins/telemetry/telemetry_impl.cpp
  src/mavsdk/plugins/transponder/transponder_impl.cpp
  src/mavsdk/plugins/tune/tune_impl.cpp
  src/mavsdk/plugins/winch/winch_impl.cpp
  templates/plugin_impl_cpp/file.j2
Labels: enhancement
